// Halloween Sale
// https://www.hackerrank.com/challenges/halloween-sale/problem?isFullScreen=false

/**
 *
 * @param {number} p the price of the first game
 * @param {number} d the discount from the previous game price
 * @param {number} m the minimum cost of a game
 * @param {number} s the starting budget
 * @return {number} The number of games that you buy during the Halloween Sale
 */
function halloweenSale(p, d, m, s) {
  let count = 0;
  while (s >= p) {
    s = s - p;
    // The price is deducted by d in each purchase.
    if (p > m) {
      p = Math.max(p - d, m);
    }
    count++;
  }
  return count;
}

/**
 *
 * @param {number} p the price of the first game
 * @param {number} d the discount from the previous game price
 * @param {number} m the minimum cost of a game
 * @param {number} s the starting budget
 */
function halloweenSale2(p, d, m, s) {
  const remainder = (p - m) % d;
  let n = 0;
  if (remainder === 0) {
    n = (p - m) / d;
  } else {
    n = Math.floor((p - m) / d) + 1;
  }
  let totalCost = ((p + (p - d * (n - 1))) * n) / 2;
  if (totalCost > s) {
    let count = 0,
      cost = p - d * (n - 1);
    while (totalCost > s) {
      totalCost -= cost;
      cost += d;
      count++;
    }
    return n - count;
  } else {
    let count = 0;
    while (totalCost + m <= s) {
      totalCost += m;
      count++;
    }
    return n + count;
  }
}

/**
 * Generated by ChatGPT.
 * @param {number} p the price of the first game
 * @param {number} d the discount from the previous game price
 * @param {number} m the minimum cost of a game
 * @param {number} s the starting budget
 */
function halloweenSale3(p, d, m, s) {
  // Step 1: If the budget is smaller than the first game price, return 0
  if (s < p) {
    return 0;
  }

  // Step 2: Calculate how many games can be bought with decreasing prices
  let n = Math.floor((p - m) / d) + 1;

  // Step 3: Calculate the total cost for the first n games
  let totalCost = ((p + (p - d * (n - 1))) * n) / 2;

  // Step 4: If total cost exceeds the budget, adjust n to fit within the budget
  if (totalCost > s) {
    let nMax = Math.floor((2 * s - p + d) / (2 * p - d));
    totalCost = ((p + (p - d * (nMax - 1))) * nMax) / 2;
    return nMax;
  }

  // Step 5: If total cost is within budget, check how many more games we can buy at price M
  let remainingBudget = s - totalCost;
  let additionalGames = Math.floor(remainingBudget / m);

  return n + additionalGames;
}

/*
Let's go through your code step by step to verify its correctness and improve its clarity.

### Problem Recap:
We want to compute how many games we can buy during the Halloween Sale, where:
- The first game costs \( P \),
- Each subsequent game costs \( D \) less until the price reaches \( M \),
- After that, every game costs \( M \),
- And you have a budget \( S \).

The goal is to find how many games you can buy without exceeding the budget.

### Analyzing Your Code:

```javascript
const remainder = (p - m) % d;
let n = 0;
if (remainder === 0) {
  n = (p - m) / d;
} else {
  n = Math.floor((p - m) / d) + 1;
}
```

#### Step 1: Calculating the number of games until the price reaches \( M \):

- You are calculating the remainder when subtracting \( m \) from \( p \) and then dividing by \( d \), which seems to determine how many steps (games) it takes for the price to reach \( M \).
  
  **This logic works correctly** for calculating how many games have prices that decrease from \( P \) down to \( M \).

- However, I would suggest making sure that you are dealing with integer division for the number of games. If \( (p - m) \) is perfectly divisible by \( d \), the formula should just return \( n \) directly.

#### Next, you calculate the total cost:

```javascript
let totalCost = (p + (p - d * (n - 1))) * n / 2;
```

This is the formula for the sum of an arithmetic progression. The sum of the first \( n \) games (with the first price \( p \) and the last price \( p - (n-1)d \)) should be calculated using:

\[
\text{Total cost} = \frac{n}{2} \times (P + (P - (n-1)D))
\]

The formula you've used looks correct for the total cost of the first \( n \) games.

#### Next, you check if the total cost exceeds the budget:

```javascript
if (totalCost > s) {
  let count = 0, cost = p - d * (n - 1);
  while (totalCost > s) {
    totalCost -= cost;
    cost += d;
    count++;
  }
  return n - count;
}
```

- Here, you're using a loop to subtract the cost of each additional game starting from the minimum price \( M \) and increasing by \( D \). This part adjusts the total cost by reducing the number of games (count) while the total cost exceeds the budget.

  **This part seems fine**, as it reduces the number of games by adjusting for the budget limitation.

#### If the total cost is within the budget:

```javascript
else {
  let count = 0;
  while (totalCost + m <= s) {
    totalCost += m;
    count++;
  }
  return n + count;
}
```

- If the total cost is less than or equal to \( S \), you are calculating how many more games can be bought at the price \( M \). This works as intended by adding \( M \) to the total cost and counting how many games you can still afford with the remaining budget.

### Suggested Improvements:

1. **Return type (floating point division):** When calculating \( n \), make sure to handle division properly (since it could result in floating-point values).

2. **Adjust while loop to avoid unnecessary checks:** The while loop subtracting cost for excess games could be replaced with a simple mathematical formula for adjustment if you're aiming for optimal performance.

3. **Consistency in variable names:** `count` represents the number of games that should be subtracted or added, which is correct, but be sure to use clear names for variables to avoid confusion.

### Optimized O(1) Approach (Without Iteration):
Here's an alternative version of the code without iteration. This avoids the loops and computes the result directly:

```javascript
function maxGames(p, d, m, s) {
  // Step 1: Calculate how many games we can buy with decreasing prices
  let n = Math.floor((p - m) / d) + 1;

  // Step 2: Calculate the total cost for the first n games
  let totalCost = (p + (p - d * (n - 1))) * n / 2;

  // Step 3: If total cost exceeds budget, adjust n to fit within budget
  if (totalCost > s) {
    let nMax = Math.floor((2 * s - p + d) / (2 * p - d));
    let totalCostAdjusted = (p + (p - d * (nMax - 1))) * nMax / 2;
    return nMax;
  }

  // Step 4: If total cost is within budget, check how many more games we can buy at price M
  let remainingBudget = s - totalCost;
  let additionalGames = Math.floor(remainingBudget / m);

  return n + additionalGames;
}
```

### Explanation of the Optimized Code:
- Step 1: Calculate the number of games that can be bought with the decreasing price.
- Step 2: Calculate the total cost for these games.
- Step 3: If the total cost exceeds the budget, use a formula to compute how many games can be bought without exceeding the budget.
- Step 4: If the total cost is within the budget, calculate how many additional games can be bought at the minimum price.

### Complexity:
- **Time Complexity:** \( O(1) \) because the solution involves only arithmetic operations and does not involve any loops or iterations.
  
Let me know if you'd like further clarification or have any more questions!



Ah, I see the issue now. The scenario where the budget is much smaller than the price of the first game needs careful handling. Thanks for pointing that out!

Let me walk you through the issue in detail and how to properly handle it:

### Problem Breakdown:
When the budget \( S \) is **smaller than the price of the first game** \( P \), we should directly return **0 games**, because you cannot afford even the first game. 

Similarly, when \( S \) is less than or equal to the cost of the first game but not enough to buy any games with decreasing prices, the approach should adjust correctly.

### Steps to Fix:

1. **Check if the budget \( S \) is smaller than the price of the first game**: If \( S \) is less than \( P \), immediately return 0, as no game can be bought.
2. **Compute how many games can be bought with decreasing prices**: This part should remain the same, as long as you ensure that the price calculation does not go negative.
3. **If the total cost exceeds the budget**, compute how many games need to be removed or adjusted in an optimal way without any loops.
4. **Finally, calculate how many additional games can be bought at price \( M \)**.

### Updated O(1) Solution

Here’s how we can fix the logic to handle small budgets, especially when \( S \) is smaller than the first game price:

```javascript
function maxGames(p, d, m, s) {
  // Step 1: If the budget is smaller than the first game price, return 0
  if (s < p) {
    return 0;
  }

  // Step 2: Calculate how many games can be bought with decreasing prices
  let n = Math.floor((p - m) / d) + 1;

  // Step 3: Calculate the total cost for the first n games
  let totalCost = (p + (p - d * (n - 1))) * n / 2;

  // Step 4: If total cost exceeds the budget, adjust n to fit within the budget
  if (totalCost > s) {
    let nMax = Math.floor((2 * s - p + d) / (2 * p - d));
    totalCost = (p + (p - d * (nMax - 1))) * nMax / 2;
    return nMax;
  }

  // Step 5: If total cost is within budget, check how many more games we can buy at price M
  let remainingBudget = s - totalCost;
  let additionalGames = Math.floor(remainingBudget / m);

  return n + additionalGames;
}
```

### Example Walkthrough: \( p = 100 \), \( d = 11 \), \( m = 10 \), \( s = 1 \)

1. **Budget Check:**  
   \( S = 1 \) is less than the first game price \( P = 100 \). So, no games can be bought, and the function should immediately return **0**.

#### Expected Output:
For \( p = 100 \), \( d = 11 \), \( m = 10 \), and \( s = 1 \), the expected result is **0** games, which is the correct output.

### Key Updates:
- **Immediate Return if \( S < P \):** If the budget is less than the first game price, we return 0 games immediately, which handles edge cases where no game can be bought.
  
---

### Time Complexity:
- The time complexity of this updated solution remains \( O(1) \), as there are no loops involved. It's still just a series of arithmetic operations to compute the result.

---

Let me know if this works for you, or if you encounter any other issues!



Absolutely! Let's break down **Step 4** in plain text so it's easier to understand.

### Scenario:
We have calculated the total cost for the first \( n \) games, but it exceeds the budget \( S \). The goal of Step 4 is to figure out how many games we can afford without exceeding the budget.

### Key Steps:
1. **Condition Check**: The first thing we do is check if the total cost of buying the first \( n \) games exceeds the budget \( S \). If it does, we need to adjust and figure out the maximum number of games we can actually buy.

2. **Formula for Adjusting \( n \)**:  
   If the total cost exceeds the budget, we want to calculate the **maximum number of games** we can afford. The tricky part is that we are dealing with an arithmetic progression (where the price decreases with each game), so we can't just use a simple formula to determine how many games we can buy. We need to work out the relationship between the total cost and the budget.

   The formula used here is:
   \[
   n_{\text{max}} = \left\lfloor \frac{2S - P + D}{2P - D} \right\rfloor
   \]
   
   **Explanation** of this formula:
   - The numerator \( 2S - P + D \) is derived from the goal of balancing the budget \( S \) with the price reduction per game \( D \) and the first game's price \( P \).
   - The denominator \( 2P - D \) represents the difference in the total cost between the first and the last game of the decreasing price sequence.

   By dividing these terms, we compute the maximum \( n \) (i.e., the maximum number of games) that we can afford while considering the decrease in price.

3. **Recompute the Total Cost**:  
   After calculating the maximum \( n_{\text{max}} \), we need to recalculate the total cost of buying the first \( n_{\text{max}} \) games (the ones that fit within the budget). This is done using the formula for the sum of an arithmetic series:

   \[
   \text{totalCost} = \frac{n_{\text{max}}}{2} \times (P + (P - D \times (n_{\text{max}} - 1)))
   \]

   This formula gives us the exact total cost for the first \( n_{\text{max}} \) games, where the prices decrease from \( P \) by \( D \) for each subsequent game.

4. **Return the Maximum Number of Games**:  
   Finally, after adjusting for the budget, we return \( n_{\text{max}} \), which is the maximum number of games that can be bought without exceeding the budget.

### In Plain English:
Step 4 is about adjusting the number of games you can afford if the total cost of the first \( n \) games exceeds your budget. We calculate the **maximum number of games** you can afford by using a formula based on the first game price \( P \), the price decrement \( D \), and your budget \( S \). Once we compute that maximum number \( n_{\text{max}} \), we recalculate the total cost for these games and return \( n_{\text{max}} \) as the answer.

### Example Walkthrough:

Let’s say we have:
- \( P = 100 \) (first game price),
- \( D = 11 \) (decrease in price per game),
- \( M = 10 \) (minimum price),
- \( S = 300 \) (budget).

If we calculated that we could afford 5 games but the total cost for those 5 games exceeds \( S \), we would use the formula in Step 4 to find the maximum number of games we can buy, which is less than 5 in this case.

### Why the Formula Works:
The formula essentially balances how much we can spend on each game considering both the decreasing price and the total budget. It ensures that we don't exceed the budget and that we buy as many games as possible, even with the price reduction.

---

Let me know if this makes sense, or if you'd like further clarification!



You're right to ask for clarification about the formula! Let me break it down more carefully.

The formula in **Step 4** you referenced is:

```javascript
nMax = Math.floor((2 * s - p + d) / (2 * p - d));
```

This formula is used to compute how many games we can afford without exceeding the budget \( S \), given that the prices of the games decrease as we buy more games.

### Let's break it down step by step.

### 1. Understanding the total cost of the first \( n \) games:
We know that the cost of the games follows an arithmetic progression:
- The first game costs \( p \),
- The second game costs \( p - d \),
- The third game costs \( p - 2d \), and so on, until the price either hits or falls below the minimum price \( m \).

The total cost of the first \( n \) games is the sum of the terms of this arithmetic progression.

The sum \( \text{totalCost} \) of the first \( n \) terms of an arithmetic progression is:

\[
\text{totalCost} = \frac{n}{2} \left( \text{first term} + \text{last term} \right)
\]

The first term is \( p \), and the last term is \( p - (n - 1) \times d \).

So, the formula for the total cost of the first \( n \) games becomes:

\[
\text{totalCost} = \frac{n}{2} \left( p + (p - (n-1) \times d) \right)
\]
\[
\text{totalCost} = \frac{n}{2} \times (2p - (n-1) \times d)
\]

This formula computes the total cost of buying the first \( n \) games.

### 2. Solving for \( n \) in terms of the budget \( S \):
Now, we want to know how many games we can afford given a budget \( S \). To do this, we need to solve for \( n \) such that the total cost of the first \( n \) games does not exceed the budget \( S \).

We want:

\[
\frac{n}{2} \times (2p - (n-1) \times d) \leq S
\]

We can simplify and solve this inequality, but we don’t want to deal with a quadratic equation. Instead, we use an approximation based on the formula for the sum of an arithmetic series.

### 3. Deriving the formula for \( n_{\text{max}} \):
By approximating the cost to match the budget \( S \), we use this formula:

\[
n_{\text{max}} = \left\lfloor \frac{2S - p + d}{2p - d} \right\rfloor
\]

#### Explanation:
- The **numerator** \( 2S - p + d \) comes from simplifying the equation for total cost and adjusting it to fit the budget. It accounts for the budget \( S \) while also considering the price \( p \) of the first game and the price decrement \( d \).
- The **denominator** \( 2p - d \) comes from the formula for the total cost of the arithmetic progression (the sum of the first \( n \) games). It represents the difference between the cost of the first game and the decrement in the price per game.

### Why it works:
This formula gives us the maximum number of games \( n_{\text{max}} \) we can afford while ensuring that the total cost does not exceed \( S \). The term \( 2S - p + d \) adjusts for the total budget, while the term \( 2p - d \) adjusts for the price progression.

### In summary:
- The numerator \( 2S - p + d \) is derived from the need to balance the budget with the total price progression.
- The denominator \( 2p - d \) accounts for the cost difference between the first and subsequent games.

The formula is designed to approximate the maximum number of games \( n \) we can afford without having to explicitly sum the costs for every possible \( n \). Instead, it leverages the properties of arithmetic progressions to give us a direct solution.

Let me know if this clears things up or if you'd like further details!
*/

module.exports = {
  halloweenSale,
  halloweenSale2,
  halloweenSale3,
};
